### ISSUE TITLE
firebase-adminエラー

### ISSUE THREAD

**Issue by okikuquai** [zamarin-dev/ipot-camera#1]
実行すると下記エラーが出る
glibcのバージョンがだめなんだろうが、環境色々いじっちゃったのでOSを入れ直してもう一度試す

```
pi@raspberrypi:~/work $ python3 ~/program/ipot-camera/getpicture.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/firebase_admin/firestore.py", line 22, in <module>
    from google.cloud import firestore # pylint: disable=import-error,no-name-in-module
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/firestore.py", line 18, in <module>
    from google.cloud.firestore_v1 import __version__
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/firestore_v1/__init__.py", line 30, in <module>
    from google.cloud.firestore_v1._helpers import GeoPoint
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/firestore_v1/_helpers.py", line 22, in <module>
    from google.api_core import gapic_v1  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/gapic_v1/__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
  File "/usr/local/lib/python3.7/dist-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/usr/local/lib/python3.7/dist-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/lib/python3.7/dist-packages/grpc/_cython/cygrpc.cpython-37m-arm-linux-gnueabihf.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/program/ipot-camera/getpicture.py", line 3, in <module>
    from firebase_admin import firestore, storage
  File "/usr/local/lib/python3.7/dist-packages/firebase_admin/firestore.py", line 28, in <module>
    raise ImportError('Failed to import the Cloud Firestore library for Python. Make sure '
ImportError: Failed to import the Cloud Firestore library for Python. Make sure to install the "google-cloud-firestore" module.
```

**Comment by okikuquai** [comment]
OS入れ直したけどダメだった
glibcをアップグレードしてみる

**Comment by okikuquai** [comment]
importからfirestoreを削除することによって動いた。そもそも必要なかった...
